[project]
name = "language-models"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "sacremoses>=0.1.1",
    "torch>=2.9.1",
    "transformers>=4.57.1",
]
